### ISSUE TITLE
branch를 나눠야할 것 같네요~~

### ISSUE THREAD

**Issue by tanibourne** [Hanhae99-clone-3team/wiselyClone_BE#20]
경문님한테 일요일 오후 전으로 해서 로그인이 가능한 서버를 띄우려고 하는데, 
로그인 서버 따로 띄워드리고, 그 이후 작업들을 진행해야하기 때문에 main,dev로 나눠서 진행하는게 적합해보입니다.
어떻게 생각하시나용?

**Comment by HoisubLee** [comment]
말씀하신 내용대로 운용해도 좋을 것 같습니다~
바로 반영하기 어려운 상황이라면 포크뜨신 브랜치에서 빌드한 내용을 서버로 띄우는 것도 임시방편이 될 것 같습니다!

**Comment by tanibourne** [comment]
넵 좋습니다!

**Comment by HoisubLee** [comment]
결국.. 메인 하나로 가게 되긴했네요 ㅎㅎ;
