### ISSUE TITLE
PR branch rule 검토

### ISSUE THREAD

**Issue by tanibourne** [Hanhae99-clone-3team/wiselyClone_BE#4]
PR  branch rule이 아직  적용 안된거 같네요!

**Comment by HoisubLee** [comment]
검토해보겠습니다!

**Comment by HoisubLee** [comment]
어제 적용한게 FE repo에만 적용된거 같네요ㅎㅎ
점심 이후에 예시코드 적용하면서 확인해보면 좋을 것 같습니다~
